name: CI

on:
  create:
    tags:
      - '*'
  push:
    branches:
      - master
  pull_request:
  schedule: 
    - cron:  '0 0 * * 1,4'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Install JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
        
    - name: Gradle Check
      run: ./gradlew check --stacktrace

    - name: Publish
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        BINTRAY_GPG_PASSPHRASE: ${{ secrets.BINTRAY_GPG_PASSPHRASE }}
      run: |
        ./gradlew :pagerduty-event-json-iterator-adapter:bintrayUpload
        ./gradlew :pagerduty-event-client:bintrayUpload
      if: success() && github.event_name == 'create'
